export const GET_ALL_SOURCES_STARTED = 'GET_ALL_SOURCES_STARTED';
export const GET_ALL_SOURCES_DONE = 'GET_ALL_SOURCES_DONE';
export const GET_ALL_SOURCES_FAILED = 'GET_ALL_SOURCES_FAILED';
export const SELECT_SOURCE_CATEGORY = 'SELECT_SOURCE_CATEGORY';