export const GET_ALL_SOURCES_STARTED = 'GET_ALL_SOURCES_STARTED';
export const GET_ALL_SOURCES_DONE = 'GET_ALL_SOURCES_DONE';
export const GET_ALL_SOURCES_FAILED = 'GET_ALL_SOURCES_FAILED';
export const SELECT_SOURCE_CATEGORY = 'SELECT_SOURCE_CATEGORY';
export const SELECT_SOURCE_LANGUAGE = 'SELECT_SOURCE_LANGUAGE';
//////////////////
export const GET_ALL_HEADLINES_STARTED = 'GET_ALL_HEADLINES_STARTED';
export const GET_ALL_HEADLINES_FAILED = 'GET_ALL_HEADLINES_FAILED';
export const GET_ALL_HEADLINES_DONE = 'GET_ALL_HEADLINES_DONE';
export const SEARCH_ALL_HEADLINES_STARTED = 'SEARCH_ALL_HEADLINES_STARTED';
export const SEARCH_ALL_HEADLINES_FAILED = 'SEARCH_ALL_HEADLINES_FAILED';
export const SEARCH_ALL_HEADLINES_DONE = 'SEARCH_ALL_HEADLINES_DONE';
